remote_theme: WildCodeSchool/workshops-jekyll-theme

titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

style: dev
title: Express - basics
description: "How to build a rest api with express"
show_clone: false
show_toc: true
lang: en
